"use strict";
var _a, _b, _c;
Object.defineProperty(exports, "__esModule", { value: true });
exports.Site = exports.PORT = exports.BASE_DIR = void 0;
const env_config_1 = require("./env_config");
(0, env_config_1.ENVCONFIG)();
const BASE_DIR = () => process.cwd() || __dirname;
exports.BASE_DIR = BASE_DIR;
exports.PORT = parseInt(process.env.PORT || "5000");
class Site {
}
exports.Site = Site;
Site.maxFlowLogWeight = parseInt(process.env.MAX_FLOW_LOG_WEIGHT || "5");
Site.isProd = process.env.MODE == "PROD";
Site.mode = Site.isProd ? "PROD" : "DEV";
Site.external = (process.env.EXTERNAL || "").split(" ").filter((x) => x.length > 0);
Site.persistenceDirectory = `storage_${process.env.PERSISTENCE_DIRECTORY || "persistence"}`;
Site.backupInterval = parseInt(process.env.BACKUP_INTERVAL_MS || "60000");
Site.interval = parseInt(process.env.CENTRAL_LOOP_INTERVAL_MS || "60000");
Site.pairInterval = parseInt(process.env.INTER_PAIR_INTERVAL_MS || "60");
Site.granularity = (_a = process.env.CENTRAL_LOOP_GRANULARITY) !== null && _a !== void 0 ? _a : "1min";
Site.externalTimeout = parseInt(process.env.EXTERNAL_TIMEOUT_MS || "30000");
Site.dataLength = parseInt(process.env.CENTRAL_LOOP_DATA_LENGTH || "100");
Site.useProxy = process.env.USE_PROXY == "true";
Site.proxyDetails = (process.env.PROXY_DETAILS || "").split(" ").filter((x) => x.length > 0);
Site.title = (_b = process.env.TITLE) !== null && _b !== void 0 ? _b : "";
Site.strategy = (_c = process.env.STRATEGY) !== null && _c !== void 0 ? _c : "BasicStrategy";
Site.directionLength = parseInt(process.env.DIRECTION_LENGTH || "5");
Site.trendSupportRatio = parseFloat(process.env.TREND_SUPPORT_RATIO || "0.5");
Site.MAPeriod = parseInt(process.env.MA_PERIOD || "5");
Site.MACDFastPeriod = parseInt(process.env.MACD_FAST_PERIOD || "12");
Site.MACDSlowPeriod = parseInt(process.env.MACD_SLOW_PERIOD || "26");
Site.MACDSignalPeriod = parseInt(process.env.MACD_SIGNAL_PERIOD || "9");
Site.StochSignalPeriod = parseInt(process.env.STOCH_SIGNAL_PERIOD || "3");
Site.StochPeriod = parseInt(process.env.STOCH_PERIOD || "14");
Site.FIPeriod = parseInt(process.env.FI_PERIOD || "14");
Site.BBPeriod = parseInt(process.env.BB_PERIOD || "14");
Site.BBStdDev = parseFloat(process.env.BB_STDDEV || "2");
Site.AOFastPeriod = parseInt(process.env.AO_FAST_PERIOD || "5");
Site.AOSlowPeriod = parseInt(process.env.AO_SLOW_PERIOD || "34");
Site.PSARMax = parseFloat(process.env.PSAR_MAX || "0.2");
Site.PSARStep = parseFloat(process.env.PSAR_STEP || "0.02");
Site.maxSignalHistoryLength = parseInt(process.env.MAX_SIGNAL_HISTORY_LENGTH || "10");
